# require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  # Enabled: false 
  Max: 120
  Details: >-
    Longer lines than 108 require scrolling when reviewing on Github. 
    But setting to 120 for development.

Style/AndOr:
  Enabled: false 
  
Style/RedundantSelf:
  Enabled: false
  
Style/SignalException: 
  EnforcedStyle: semantic

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 30
  
Metrics/MethodLength:
  Max: 50
  Details: >-
    This is the max that will fit in one screen.   
  
Style/FrozenStringLiteralComment:
  Enabled: false 
  
Style/StringLiterals:
  Enabled: false 
  
Style/Documentation:
  Enabled: false 
  Details: >-
    This would be ideal in a multi-person project. 
    
Style/GuardClause:
  Details: >-
    This should remain active as it flags methods that do not return if nothing is done.
    
Metrics/AbcSize:
  Max: 18
  Details: >-
    Increased this to give more wiggle room for my code.
    
Bundler/OrderedGems:
  Enabled: false
  
Style/ClassVars:
  Enabled: false
  Severity: warning
  
Style/FormatStringToken:
  Enabled: false
  Details: >-
    Results in too many false positives when used with validations. 
  
## New cops:
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true 

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
  
Lint/RaiseException:
  Enabled: true 
  
Lint/StructNewOverride:
  Enabled: true
  
Style/ExponentialNotation:
  Enabled: true 
  
Style/HashEachMethods:
  Enabled: true 
  
Style/HashTransformKeys:
  Enabled: true 
  Severity: warning
  
Style/HashTransformValues:
  Enabled: true
  Severity: warning
  
Style/SlicingWithRange:
  Enabled: false
  Details: >-
    Too modern. I like the -1.